SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `CIFPAY_LC` MODIFY COLUMN `LC_FREEZING_AMOUNT`  decimal(19,2) NULL DEFAULT 0.00 COMMENT '银信证冻结金额(单位分)，系统冻结金额，而非银行的冻结金额，包含已履约和已申请解付的金额' AFTER `LC_AMOUNT`;

ALTER TABLE `CIFPAY_LC` MODIFY COLUMN `PAYER_TYPE`  varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '开证人类型：个人:PERSONAL  企业:ENTERPRISE' AFTER `PAYER_ACCNO`;

ALTER TABLE `CIFPAY_LC` MODIFY COLUMN `LC_STATUS`  varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '银信证状态：10已开证、20已收证、30已履约、31部分履约、32已展期、40已申请解付、41已刹车、50已执行解付、88已解付完成、90已解冻退回、91预失效' AFTER `RECV_MOBILE`;

ALTER TABLE `CIFPAY_LC` MODIFY COLUMN `PAY_VALID_TIME`  timestamp NULL DEFAULT NULL COMMENT '执行解付有效期（到期执行解付）' AFTER `CONFIRM_VALID_TIME`;

CREATE TABLE `CIFPAY_LC_ACC` (
`LC_ACC_ID`  bigint(20) NOT NULL ,
`LC_ID`  bigint(20) NULL DEFAULT NULL ,
`LC_OPEN_AMT`  decimal(19,2) NULL DEFAULT 0.00 COMMENT '银信证开证金额' ,
`LC_FREEZE_AMT`  decimal(19,2) NULL DEFAULT 0.00 COMMENT '银信证冻结金额' ,
`LC_AVAILABLE_AMT`  decimal(19,2) NULL DEFAULT 0.00 COMMENT '银信证可用余额' ,
`LC_APPOINTMENT_AMT`  decimal(19,2) NULL DEFAULT 0.00 COMMENT '银信证履约金额' ,
`CHANGE_AMT`  decimal(19,2) NULL DEFAULT 0.00 COMMENT '变化金额' ,
`BIZ_TABLE`  varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '业务操作的表名' ,
`BIZ_SEQNO`  bigint(20) NULL DEFAULT NULL COMMENT '业务操作ID' ,
`CREATE_TIME`  timestamp NULL DEFAULT CURRENT_TIMESTAMP ,
`REMARK`  varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`LC_ACC_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=Compact
;

ALTER TABLE `CIFPAY_LC_CONFIRM_PAY` MODIFY COLUMN `VALID_TIME`  timestamp NULL DEFAULT NULL COMMENT '申请解付有效期时长（到期执行解付）' AFTER `ORDER_ID`;

ALTER TABLE `CIFPAY_LC_CONFIRM_PAY` MODIFY COLUMN `CONFIRM_STATUS`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '处理结果：申请解付成功、失败、0处理中' AFTER `SIGN_CODE`;

ALTER TABLE `CIFPAY_LC_CONFIRM_PAY` ADD COLUMN `PROCESS_STATUS`  int(11) NULL DEFAULT NULL COMMENT '流程状态：0待处理、50已由执行解付处理、41已由刹车处理、90已由失效处理' AFTER `CONFIRM_STATUS`;

ALTER TABLE `CIFPAY_LC_CONFIRM_PAY` DROP COLUMN `OPT_TYPE`;

ALTER TABLE `CIFPAY_LC_CONFIRM_PAY` DROP COLUMN `FLAG_PAY`;

ALTER TABLE `CIFPAY_LC_INVALID` MODIFY COLUMN `INVALID_TYPE`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '失效类型：1=撤回失效、2=退回失效、3=强制失效（我方客服操作）、4=到期失效' AFTER `LC_ID`;

ALTER TABLE `CIFPAY_LC_OPEN` MODIFY COLUMN `VALID_TIME`  timestamp NULL DEFAULT NULL COMMENT '开证有效期' AFTER `RECV_MOBILE`;

ALTER TABLE `CIFPAY_LC_PAGE` ADD COLUMN `VERSION`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '版本号' AFTER `LC_ID`;

ALTER TABLE `CIFPAY_LC_PAGE` ADD COLUMN `STORE_TYPE`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '存储方式，fastdfs、阿里云等' AFTER `PAGE_URI`;

ALTER TABLE `CIFPAY_LC_PAGE` ADD COLUMN `STORE_PATH`  varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '存储的物理路径' AFTER `STORE_TYPE`;

ALTER TABLE `CIFPAY_LC_PAGE` ADD COLUMN `STORE_GROUP`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'fastdfs需要有group' AFTER `STORE_PATH`;

ALTER TABLE `CIFPAY_LC_PAGE` MODIFY COLUMN `TRAN_STATUS`  int(1) NOT NULL DEFAULT 0 COMMENT '处理标志，0=待处理；1=处理中；2=处理成功，3=处理失败' AFTER `STORE_GROUP`;

ALTER TABLE `CIFPAY_LC_PAGE` ADD COLUMN `LOCKED_BY_NODE`  varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '当前锁定该记录的应用节点ID' AFTER `GEN_TIME`;

CREATE TABLE `CIFPAY_LC_PAGE_TEMPLATE` (
`TEMPLATE_CODE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '模板编号' ,
`VERSION`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '版本号' ,
`TRAN_STATUS`  int(1) NOT NULL DEFAULT 0 COMMENT '处理状态，0=无进程占用处理；1=处理中' ,
`LOCKED_BY_NODE`  varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '当前锁定该记录的应用节点ID' ,
`CREATE_TIME`  datetime NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '创建时间' ,
`UPDATE_TIME`  datetime NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '更新时间' ,
PRIMARY KEY (`TEMPLATE_CODE`, `VERSION`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=Compact
;

CREATE TABLE `CIFPAY_LC_PAGE_TEMPLATE_DETAIL` (
`TEMPLATE_CODE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '模板编号' ,
`VERSION`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '版本号' ,
`TEMPLATE_FILE_NAME`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '模板文件名称' ,
`TEMPLATE_FILE_PATH`  varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '原始模板文件全路径' ,
`SYS_FILE_PATH`  varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '上传后文件全路径' ,
`ITEM_NAME`  varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '在模板文件中的唯一标识名称，##name##' ,
`ITEM_CATEGORY`  varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分类，非静态引入资源与业务相关。如果此项不为空则ITEM_NAME与字典项相对应' ,
`SEQ`  int(11) NULL DEFAULT NULL COMMENT '【重要】次序号，后上传的模板文件里面可能引用先上传的文件路径。通常情况下图片资源要先上传，然后css和js，最后才是网页模板' ,
`CREATE_TIME`  timestamp NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (`TEMPLATE_CODE`, `VERSION`, `TEMPLATE_FILE_NAME`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=Compact
;

ALTER TABLE `CIFPAY_LC_PRODUCT` MODIFY COLUMN `PAYER_TYPE`  varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '开证人类别：10个人、20企业、30全部' AFTER `LC_STANDARD`;

ALTER TABLE `CIFPAY_LC_PRODUCT` MODIFY COLUMN `RECV_TYPE`  varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '收证人类别：10个人、20企业、30全部' AFTER `PAYER_ACCNO_TYPE`;

ALTER TABLE `CIFPAY_LC_PRODUCT` MODIFY COLUMN `LC_INVALID_HANDLE_CHANNEL`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '9' COMMENT '银信证失效处理渠道，1=银行标准；9=其他，（暂时保留，用于区分星意和标准版）' AFTER `THIRD_PARTY_CODE`;

ALTER TABLE `CIFPAY_LC_PRODUCT` ADD COLUMN `AUTO_OPEN`  bit(1) NULL DEFAULT NULL COMMENT '自动开证' AFTER `ALLOW_PARTIAL_PAY`;

ALTER TABLE `CIFPAY_LC_PRODUCT` MODIFY COLUMN `PRODUCT_STATUS`  varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '0未生效、1已生效、2已停用、3审批中' AFTER `VALID_TIME`;

ALTER TABLE `CIFPAY_LC_PRODUCT` MODIFY COLUMN `DEL_FLAG`  bit(1) NOT NULL DEFAULT b'0' COMMENT '删除标识' AFTER `PRODUCT_STATUS`;

ALTER TABLE `CIFPAY_LC_PRODUCT` DROP COLUMN `ALLOW_MULTIPLE_UPDATE`;

ALTER TABLE `CIFPAY_LC_PRODUCT` DROP COLUMN `AUTO_INVALID`;

ALTER TABLE `CIFPAY_LC_SEND` MODIFY COLUMN `LC_BALANCE`  decimal(19,2) NULL DEFAULT NULL COMMENT '银信证当前余额（单位分）' AFTER `LC_CONFIRM_AMOUNT`;

ALTER TABLE `CIFPAY_LC_SEND` ADD COLUMN `PROCESS_STATUS`  int(11) NULL DEFAULT NULL COMMENT '流程状态：0待处理、32已由展期处理、40已由申请解付处理、90已由失效处理' AFTER `SEND_STATUS`;

ALTER TABLE `CIFPAY_PRE_LC` MODIFY COLUMN `ORDER_ID`  varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '订单号' AFTER `MID`;

ALTER TABLE `CIFPAY_PRE_LC` MODIFY COLUMN `LC_STATUS`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '银信证状态，00新建、88交易成功、99交易失败' AFTER `RECV_MOBILE`;

CREATE TABLE `CIFPAY_THIRD_ICBCBANKENT_PAYENT` (
`BATCH_SEQNO`  varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`DETAIL_SEQNO`  varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`CALLER_CODE`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '调用者（应用系统）的唯一代码，CIFPAYLC代表调用者为银信证核心业务应用' ,
`CALLER_INSTRUCTION_NO`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '调用者应用系统的为该交易定义的唯一批次号，该批次号在调用者应用系统内部必须保证唯一' ,
`CALLER_INSTRUCTION_DETAIL_NO`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '调用者应用系统的为每笔交易指令明细定义的序号，必须保证在批次号内唯一' ,
`PAY_ENTERPRISE_CODE`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '付款方企业代码，例如XDS表示使用星电商公司的账号作为付款方' ,
`TRAN_DATE`  varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易日期yyyyMMdd' ,
`TRAN_TIME`  varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易时间hhmmssaaabbb精确到微秒' ,
`CURRENCY_CODE`  varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '银信证定义币种代码，CNY人民币' ,
`ICBC_CURRENCY_TYPE`  varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '工行定义的币种代码，001人民币' ,
`PAY_AMT`  decimal(17,0) UNSIGNED NOT NULL COMMENT '金额，无正负号，不带小数点，以分作单位' ,
`ICBC_CIS`  varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '集团CIS号，银企客户注册时的归属编码' ,
`ICBC_BANK_CODE`  varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '归属银行编号，银企客户注册时的归属单位' ,
`ICBC_CERT_ID`  varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '证书ID' ,
`ICBC_PAY_TYPE`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '记账处理方式，1加急，2普通' ,
`PAY_ACCOUNT_NO`  varchar(19) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '本方账号，即付方账号' ,
`RECV_BANK_CODE`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '收款银行代码，对应LC_BANK表' ,
`RECV_BANK_NAME`  varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易对方银行名称，长度不能超出银行限制' ,
`RECV_BANK_CITY_NAME`  varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '收款方所在城市名称' ,
`RECV_ACCOUNT_NO`  varchar(34) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '对方账号' ,
`RECV_ACCOUNT_NAME`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '对方账户名称' ,
`FUND_USE_DESC`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '用途中文描述' ,
`SUMMARY`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '摘要' ,
`CORPORATE_PERSONAL_FLAG`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '对公对私标志，0对公账户，1个人账户' ,
`CROSS_BANK_FLAG`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '系统内外标志，1系统内，2系统外' ,
`SAME_CITY_FLAG`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '同城异地标志，1同城，2异地' ,
`TXN_RESULT_STATUS`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易结果状态，N新交易待处理，S银行交易成功，F银行交易失败，P银行处理中，U交易结果暂不明确' ,
`BANK_RET_BATCH_SERIAL_NO`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '平台交易流水号，银行产生的银行批次号' ,
`BANK_RET_DETAIL_ORDER_NO`  varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '银行产生的批次内的小序号，和银行产生的批次组合后在银行端对应唯一一笔交易明细' ,
`BANK_ORI_DETAIL_RESULT_CODE`  varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`BANK_ADDI_BATCH_RETURN_CODE`  varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`BANK_ADDI_BATCH_RETURN_MSG`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`BANK_ADDI_DETAIL_RETURN_CODE`  varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`BANK_ADDI_DETAIL_RETURN_MSG`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`BATCH_SEQNO`, `DETAIL_SEQNO`),
UNIQUE INDEX `UDX_PAYENT_01` (`BATCH_SEQNO`, `DETAIL_SEQNO`) USING BTREE ,
UNIQUE INDEX `UDX_PAYENT_02` (`CALLER_CODE`, `CALLER_INSTRUCTION_NO`, `CALLER_INSTRUCTION_DETAIL_NO`) USING BTREE 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=Compact
;

SET FOREIGN_KEY_CHECKS=1;

